name: lwnet_reproduce
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.3.1
  - torchvision=0.4.2
  - cudatoolkit=10.0
  - numpy=1.19.1
  - pillow=7.2.0
  - scipy=1.5.2
  - scikit-image=0.16.2
  - scikit-learn=0.23.2
  - pandas=1.1.1
  - matplotlib=3.3.1
  - imageio=2.9.0
  - pyyaml=5.3.1
  - tqdm=4.48.2
  - joblib=0.16.0
  - networkx=2.5
